python gerar_instancia.py A 1
python gerar_instancia.py A 2
python gerar_instancia.py A 3
python gerar_instancia.py A 4
python gerar_instancia.py A 5
python gerar_instancia.py A 6
python gerar_instancia.py A 7
python gerar_instancia.py A 8
python gerar_instancia.py A 9
python gerar_instancia.py A 10
python gerar_instancia.py A 11
python gerar_instancia.py A 12
python gerar_instancia.py A 13
python gerar_instancia.py A 14
python gerar_instancia.py A 15
