python gerar_instancia.py B 1
python gerar_instancia.py B 2
python gerar_instancia.py B 3
python gerar_instancia.py B 4
python gerar_instancia.py B 5
python gerar_instancia.py B 6
python gerar_instancia.py B 7
python gerar_instancia.py B 8
python gerar_instancia.py B 9
python gerar_instancia.py B 10
python gerar_instancia.py B 11
python gerar_instancia.py B 12
python gerar_instancia.py B 13
python gerar_instancia.py B 14
python gerar_instancia.py B 15
python gerar_instancia.py B 16
python gerar_instancia.py B 17
python gerar_instancia.py B 18
python gerar_instancia.py B 19
python gerar_instancia.py B 20
python gerar_instancia.py B 21
python gerar_instancia.py B 22
python gerar_instancia.py B 23
python gerar_instancia.py B 24
python gerar_instancia.py B 25

